# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: 805 Developers Hub

# Short description (goes below the title; it will also be used in the RSS feed)
description: A language agnostic meetup for developers of all levels in the 805 area to learn and build software projects together.

# Your name, as you want it to appear underneath each post and in the footer
author: 805 Developers Hub

# Your email if you want it to be linked on the contact page
author_email: 805developershub@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://805developershub.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, node_modules]

# Custom site props

# Google analytiucs id
google_analytics_id: UA-88458304-1

# Weekely meetup metadata
meetup_date_text: January 26, 2017
meetup_location_text: Join us at Hub 101, 31416 Agoura Rd #105, Westlake Village, CA 91361
meetup_description_text: We'll be working on personal projects and talking about all things code and development related.

# Global copyright footer text
copyright_text: Copyright &copy; 805 Developers Hub. All Rights Reserved.

# Social media urls
twitter_url: https://twitter.com/805devhub
github_url: https://github.com/805developershub
meetup_url: https://www.meetup.com/LearnToCodeLA/
slack_url: https://slackin-qkkdtfdvoc.now.sh
